name: Xcode notarizer
description: Notarize Xcode products using notarytool
branding:
  icon: "heart"
  color: "purple"
inputs:
  product-path:
    description: |
      Path to the product
      Support .app, .dmg and .pkg
      Would create temporary .zip file if using .app product
    required: true
  apple-id:
    description: |
      Apple ID of the developer
      should also specify app-password and team-id
    required: false
  app-password:
    description: |
      App specific password of the product
      should also specify apple-id and team-id
    required: false
  team-id:
    description: |
      Developer team ID of the product
      should also specify apple-id and app-password
    required: false
runs:
  using: "composite"
  steps:
    - name: Notarize application bundle
      shell: python3 {0}
      run: |
        import json
        import os
        import subprocess
        temp_filename = './forNotarize.zip'
        os.system(
            'ditto -c -k --sequesterRsrc --keepParent '
            './${{ inputs.product-name }}.app ' +
            temp_filename
        )
        result = json.loads(
            subprocess.run(
                'xcrun notarytool submit ' + temp_filename +
                ' --output-format json --wait'
                ' --apple-id "${{ inputs.account-username }}"'
                ' --password "${{ inputs.account-password }}"'
                ' --team-id "${{ inputs.team-id }}"',
                stdout=subprocess.PIPE,
                shell=True
            ).stdout.decode('utf-8')
        )
        print(result)
        if result['status'] == 'Accepted':
            os.system('xcrun stapler staple ./${{ inputs.product-name }}.app')
            os.remove(temp_filename)
        else:
            print('Notarization failed: ' + result['message'])
            exit(1)
